name: flutterfire_gen_annotation
description: flutterfire_gen_annotation
version: 0.4.1
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.3
