name: flutterfire_gen
description: flutterfire_gen is a package for automatic code generation for Cloud Firestore. It supports efficient CRUD operations with type-safe interfaces and methods.
version: 0.5.0
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ">=6.11.0 <8.2.0"
  build: ^4.0.0
  cloud_firestore: ^6.0.2
  flutter:
    sdk: flutter
  flutterfire_gen_annotation:
    git:
      url: https://github.com/geovaniprodata/flutterfire_gen.git
      path: packages/flutterfire_gen_annotation
  
  flutterfire_gen_utils:
    git:
      url: https://github.com/geovaniprodata/flutterfire_gen.git
      path: packages/flutterfire_gen_utils
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.1
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.8.0
  mockito: ^5.4.4
  test: ^1.24.0

# https://dart.dev/tools/pub/pubspec#platforms
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
